<script setup>
import Navbar from '../components/Navbar.vue';
</script>

<template>
    <div class="agriculture-container">
      <Navbar />
      <h1>Key Finding 1: The Methodology Becomes More Elaborate</h1>
      <h2>1. Expanded and Refined Indicators</h2>
      <p>Compared to The Methodology for 2021 Food and Agriculture Benchmark, the 2023 WBA Food and Agriculture Benchmark methodology has significantly expanded the breadth and depth of its indicators, covering 46 more detailed metrics. These new and revised indicators aim to more accurately assess companies' performance in environmental, social, and governance (ESG) areas, reflecting the latest industry best practices and scientific developments.</p>
      <h3>1.1 The Added Indicator “Lobbying and Advocacy”</h3>
      <p>In 2021, the Governance and Strategy Sector focused more on the company itself, its sustainable targets, and business model. However, in 2023, WBA found the importance of the external effect of companies. Hence, this indicator which primarily assessed whether companies disclosed basic information about lobbying activities and policy advocacy is included in the latest assessment. It has been refined into multiple dimensions, requiring companies not only to disclose their lobbying activities but also to provide detailed explanations of whether their policy advocacy aligns with sustainable development goals.</p>
      <p>For Chinese companies, the impact of this change primarily lies in the requirements for information disclosure and alignment with policy goals. Traditionally, Chinese companies have placed more emphasis on operational practices, and their information disclosure habits may lag behind international standards. Specifically, with regard to disclosing lobbying or policy advocacy activities, some companies may lack systematic record-keeping and reporting processes, and they may not be adequately prepared in terms of disclosure. The indicator also requires companies to disclose their involvement in industry associations and to explain whether these associations support sustainability-related policies. In China, many industry associations lack transparency, and companies participating in them may not have clear public information or policy support records, which puts Chinese companies at a disadvantage when it comes to this indicator.</p>
      <p>In the 2023 reassessment, 19 of 27 Chinese companies got no score in this new indicator, only Want Want China met more than three elements and got 0.43. Want Want China performed well in the "Lobbying and Advocacy" category by focusing on transparent stakeholder engagement, robust governance practices, and aligning its ESG strategy with long-term sustainability goals. The company maintains regular communication with government agencies, regulators, and business partners, ensuring its policy advocacy is transparent and well-integrated with sustainability objectives. Additionally, Want Want China’s ESG Committee plays a key role in ensuring that advocacy efforts align with global standards, particularly in areas of anti-corruption and ethical business practices.</p>
      <h3>1.2 Unconditional Scoring Approach: Independent Indicator Assessment Fosters Target ESG Improvements</h3>
      <p>The Unconditional Scoring Approach introduced in the 2023 WBA Food and Agriculture Benchmark marks a significant change in the way companies' ESG performance is evaluated. Unlike the 2021 methodology, which often uses a cumulative scoring system, the 2023 approach assesses each indicator independently, allowing companies to earn points for meeting specific elements of an indicator, regardless of their performance in other areas. Companies are no longer penalized for underperforming in one area if they excel in another. Each element in an indicator is evaluated on its own merit, meaning that companies can earn points based solely on their performance in that particular category. This change enhances transparency and fairness by helping companies identify their strengths and weaknesses and focus on improving specific areas without the overall score being dragged down by underperformance in other categories.</p>
      <p>However, in the other hand, this means stricter scoring standards. By assessing each indicator independently and in more detail, companies are required to demonstrate tangible progress in specific ESG areas rather than relying on overall strong performance to offset weaker areas. The detailed focus on individual indicators forces companies to address specific weaknesses. They cannot mask the lack of qualitative or quantitative information disclosure behind exhaustive goals. This creates pressure to improve holistically across all ESG dimensions.</p>
      <h2>2. Capitalizing on Turbulence: Strategic ESG Advancement for Chinese Companies</h2>
      <p>In the wake of changes to the WBA methodology, the global average score for 350 companies dropped from 19.54 to 17.39, while the average score for 25 Chinese companies only fell from 12.47 to 11.51. This data suggests that the global trend towards stricter ESG standards poses significant challenges for all companies, but the impact on Chinese companies has been relatively less pronounced. The smaller drop in scores for Chinese companies reflects their initial lower baseline in ESG practices, indicating that they have not yet fully developed comprehensive systems for meeting higher sustainability standards. However, the consistent gap between global and Chinese companies' performance highlights the need for Chinese firms to accelerate their progress in governance, transparency, and sustainability efforts. As global ESG expectations continue to rise, Chinese companies must address these challenges to remain competitive in the international market. The relatively smaller decrease in their scores also indicates that there is substantial room for improvement, and with appropriate strategic efforts, Chinese companies have the potential to narrow the gap with global counterparts.</p>
      <h1>Key Finding 2: Increasing Divergence in ESG Performance Among Chinese Food and Agriculture Companies</h1>
      <h2>1. Polarization of Score Changes</h2>
      <p>Among the 25 Chinese food and agriculture companies that were both assessed in 2021 and 2023, although their average score increased, 13 companies saw their ESG scores decline, and 2 companies maintained a score of zero across both years. This polarization highlights the significant differences in the performance of Chinese companies regarding sustainable development and social responsibility.</p>
      <h2>2. Why the polarization is increasing?</h2>
      <h3>2.1 Differences in Governance and Strategy</h3>
      <p>Upon reviewing the companies that improved their scores, it is evident that they typically scored higher in the Governance and Strategy category, indicating they have stronger governance structures and are better equipped to execute sustainability strategies. These companies not only integrate sustainability goals into the core of their business operations, but also foster strong collaborations with stakeholders through transparent communication. By aligning their strategic goals with sustainability objectives, such companies create a positive feedback loop, allowing them to better adapt to market changes and improve their ESG performance over time.</p>
      <p>In contrast, companies with declining scores often struggle with weak strategy execution, insufficient resource allocation, or a lack of leadership attention to sustainability. These companies find it difficult to keep pace with rapidly evolving market conditions and regulatory demands. Even though some companies take sustainability-related actions, they still fail to align with market expectations, resulting in stagnant or declining ESG performance.</p>
      <h3>2.2 Industry and Scale Differences</h3>
      <p>Large multinational corporations like China Mengniu Group and FCF Co., Ltd. have a global presence and are more inclined to adhere to international ESG standards, investing substantial resources in sustainability initiatives. Their global operations provide stronger incentives and capabilities to address environmental and social issues.</p>
      <p>Conversely, smaller companies such as Beidahuang Group, which is more domestically focused, face more challenges in implementing ESG strategies. These companies often lack the resources and international experience to meet higher ESG standards. Additionally, some Chinese companies only base their ESG reports on Chinese environmental regulations or the HKEX ESG Reporting Guide. This often results in incomplete information disclosure, which fails to meet the WBA’s disclosure requirements, leading to lower scores. The divergence between 2019 and 2023 has been exacerbated by rising global expectations for ESG standards, which larger companies have been better positioned to meet, while smaller companies have struggled to adapt.</p>
      <h2>3. Impact of Increasing Divergence</h2>
      <h3>3.1 Impact on Corporate Reputation</h3>
      <p>A company’s ESG performance directly influences its market reputation and investor confidence. Since the Food and Agriculture industry involves the entire supply chain from the farm to the fork, more and more investors prioritize ESG criteria in their decision-making processes. Companies with higher ESG scores are more likely to attract capital and build a positive brand image with consumers and partners. Conversely, companies with declining scores face the risk of reputational damage and missed investment opportunities, potentially being excluded from critical supply chain partnerships.</p>
      <h3>3.2 Long-Term Impact on Chinese Food and Agriculture Industry</h3>
      <p>The increasing divergence in ESG performance will impact the overall progress of the Chinese food and agriculture industry. High-performing companies will set higher standards, but the widening gap may slow the sector’s collective movement toward sustainability. If many companies continue to lag behind in meeting ESG standards, the entire Chinese industry could face stricter regulatory scrutiny. This would increase operational costs and reduce international competitiveness. Additionally, companies failing to meet these standards may lose access to global supply chains and market opportunities, ultimately weakening the industry's position in international markets.</p>
      <h2>4. Future Opportunities and Challenges</h2>
      <p>The growing divergence in ESG performance presents both opportunities and challenges for Chinese food and agriculture companies. Companies leading in sustainability have the chance to consolidate their market positions through continued ESG investments, leveraging their leadership to capture greater market share and enhance brand equity. Meanwhile, companies with lower scores must prioritize improving their governance structures, enhancing environmental policies, and fulfilling social responsibilities to remain competitive in an evolving market landscape.</p>
    </div>
  </template>